# Generated by Django 5.1.5 on 2025-01-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocje', '0002_rename_date_checked_pricehistory_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('aktualna_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ostatnia_aktualizacja', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaCen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_sprawdzenia', models.DateTimeField(auto_now_add=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocje.produkt')),
            ],
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
