# Generated by Django 5.1.5 on 2025-01-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocje', '0003_produkt_historiacen_delete_pricehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='cena_docelowa',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='aktualna_cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
