# Generated by Django 5.1.5 on 2025-01-27 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocje', '0004_produkt_cena_docelowa_alter_produkt_aktualna_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiacen',
            name='produkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='promocje.produkt'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena_docelowa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
