# Generated by Django 5.1.5 on 2025-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocje', '0005_alter_historiacen_produkt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='email_odbiorcy',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
